{
  "sources": [
    {
      "path": "docs/architecture.md",
      "role": "primary"
    },
    {
      "path": "docs/requirements.md",
      "role": "authoritative"
    },
    {
      "path": "docs/constraints.md",
      "role": "constraints"
    }
  ]
}
